### PR TITLE
move _worker_thread from class attribute to object attribute

### LINKED ISSUE #24: Can't create two handlers with different configurations
```python
import logging
import sys
from logstash_async.handler import AsynchronousLogstashHandler


host = 'localhost'

test_logger1 = logging.getLogger('python-logstash-logger')
test_logger1.setLevel(logging.INFO)
test_logger1.addHandler(AsynchronousLogstashHandler(
    host,
    5002,
    database_path=None,
    transport='logstash_async.transport.UdpTransport'
))

test_logger1.info('logger1')


test_logger2 = logging.getLogger('python-logstash-logger2')
test_logger2.setLevel(logging.INFO)
test_logger2.addHandler(AsynchronousLogstashHandler(
    host,
    5000,
    database_path=None,
    transport='logstash_async.transport.UdpTransport'
))


test_logger2.info('logger2')  # goes to 5002 port :(
```

I think problem is here:
```python
 class AsynchronousLogstashHandler(Handler):
     """Python logging handler for Logstash. Sends events over TCP by default.
     :param host: The host of the logstash server, required.
     :param port: The port of the logstash server, required.
     :param database_path: The path to the file containing queued events, required.
     :param transport: Callable or path to a compatible transport class.
     :param ssl_enable: Should SSL be enabled for the connection? Default is False.
     :param ssl_verify: Should the server's SSL certificate be verified?
     :param keyfile: The path to client side SSL key file (default is None).
     :param certfile: The path to client side SSL certificate file (default is None).
     :param ca_certs: The path to the file containing recognized CA certificates.
     :param enable: Flag to enable log processing (default is True, disabling
                   might be handy for local testing, etc.)
     :param event_ttl: Amount of time in seconds to wait before expiring log messages in
                       the database. (Given in seconds. Default is None, and disables this feature)
     """
 
     _worker_thread = None
...
```

`_worker_thread` -- class based attribute and shares between different handlers

### PR DESCRIPTION
**Pull request by d1skort**
Hello! Thanks for the great library :)

I want to resolve #24 issue

### CODE REVIEW

**Comment by eht16** [comment]
Thread-safety isn't the only issue though I'm not sure whether there is a real problem with thread-safety, where do your doubts go?
A clear problem is `LogProcessingWorker.memory_cache` which is shared between the instances and so not thread-safe. This maybe could be easily solved using `threading.local()`.

There might be problems with the housekeeping of the worker threads, this needs deeper inspection and testing.

My initial intention was to store the worker thread as a class attribute as some sort of a singleton as I wanted to ensure a single worker thread for the whole application (to be precise: the whole process).
Your use case is clearly different.

Possible workaround:
As long as you use the same Logstash instance for both handlers, you could bind different formatter instances to the handlers and configure the formatters with different `message_type`s (or use tags) to later differentiate the events in Logstash while transmitting them over the same port with one worker thread.

**Comment by d1skort** [comment]
Thanks for the answer! 

I am going to try this workaround, yes. But also, I need to reconfigure my logstash instance :(

btw, why we should keep one global dict instance for memory cache? Can we just create dict in `MemoryCache.__init__`? I think, it would be totally thread-safe.

**Comment by eht16** [comment]
Good point.
I think the initial idea was to have a global cache even if the worker thread is not running or restarted. Though this should never happen, at least not in normal conditions.

See #25 for an alternative approach: setting the cache in the worker thread. The outcome should be the same as initializing it in `MemoryCache.__init__` but keeps the `MemoryCache` class more flexible in general as it still receives a cache instance from the caller.

Would you mind testing the changes? I didn't as I don't use a in-memory database.
Also CC'ing @loganasherjones as he initially implemented this.

**Comment by loganasherjones** [comment]
Yeah, the only reason I made the cache a global was to allow people to persist their messages through the threads dying or object deletion.

**Comment by eht16** [comment]
@d1skort fine by me, no hurries.

**Pull request closed without merging**
